### ISSUE TITLE
Does not handle tempo changes

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/midi-file-slicer#257]
If I'm not mistaken, [looking at the code](https://github.com/chrisguttandin/midi-file-slicer/blob/master/src/midi-file-slicer.ts#L14), there is only a single tempo that is kept for the whole file. This means that any tempo change will be ignored. Is this correct?

For example, [check this MIDI file](https://github.com/chrisguttandin/midi-file-slicer/files/10952029/blue-bag-folly.zip) that features a tempo change at measure 15.

**Comment by chrisguttandin** [comment]
You're absolutely right. Thanks for making me aware of it.

I changed the code to handle multiple set tempo events. It even made the computation a little more accurate.

Now it doesn't really make sense anymore that the `MidiFileSlicer` is a class but I left it as is for now to not introduce any breaking changes.

v6.0.76 contains the update.

Thanks again.

**Comment by infojunkie** [comment]
Sorry to bother you again, but the latest version did not work as a drop-in replacement in `midi-player`. I didn't debug the issue, because I had produced my own fix to handle tempo changes: https://github.com/infojunkie/midi-player/commit/862b8c470e9d85df92c3ea208dab2cf4be9f8316

**Comment by chrisguttandin** [comment]
Thanks for letting me know. I found a bug which happened when a file has multiple tracks and one of them is finished before the other. https://github.com/chrisguttandin/midi-file-slicer/commit/f7164bdd5e6db17e1c40ce3eccbb458ac279e0a3

Hopefully that was the issue you ran into.

v6.0.77 has the fix.

**Comment by infojunkie** [comment]
Thanks, the latest version fixed the issue for me.
